### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kwaazaar** [weaveworks/kured#104] opened 2019-12-16 08:11 UTC
Readme describes the use of the 1.2 image, but also describes the scheduling parameters which, as I just found out, are not included in release 1.2. 

It's been a while, so when can we expect a new release?

**Comment by rnarayana** [comment] 2020-01-09 04:26
I deployed it directly from master and it is working fine for the last 1 month. Wonder why the release was not created?

**Comment by dholbach** [comment] 2020-01-20 13:05
Duplicate of #97.

**Closed by dholbach** 2020-01-20 13:05 UTC
