### ISSUE TITLE
alertFilterRegexp not handled properly

### ISSUE THREAD

**Issue by WimDiepgrond** [weaveworks/kured#174] opened 2020-08-17 10:01 UTC
If I use prometheus to check for existing alerts and also filter on alerts that should be ignored using the "alertFilterRegexp" kured still keep from rebooting because of alerts that exist. These alerts are however in the ignore filter that I use.

If I for example use ```alertFilterRegexp: ^(RebootRequired|Watchdog)``` and I have an Alert for "Watchdog" the node can't be rebooted and in the logs I see: 
level=warning msg="Reboot blocked: 2 active alerts: [RebootRequired Watchdog]"

Cause (I think): in the Helm chart quotes are added to the filter value in the daemonset:
          {{- if .Values.configuration.alertFilterRegexp }}
            - --alert-filter-regexp={{ .Values.configuration.alertFilterRegexp | **_quote_** }}
          {{- end }}
which results in:
- --alert-filter-regexp="^(RebootRequired|Watchdog)$"

If I then manually edit the daemonset after install of the chart and remove the quotes around the filter value everything works fine.
- --alert-filter-regexp=^(RebootRequired|Watchdog)$

Either the code should consider the quotes or the helm chart should be adjusted I guess.

**Comment by SerialVelocity** [comment] 2020-08-20 20:11
I've just hit this as well.

I worked around it with:
```
alertFilterRegexp: 'ABC$|^CephOSDNearFull$|^ABC'
```

A massive hack but since I use `helm-operator` to deploy these, I lose any changes I make to the daemonset every hour.

**Comment by ckotzbauer** [comment] 2020-08-21 04:56
Duplicate of #166

**Closed** 2020-08-21 07:31 UTC

**Comment by WimDiepgrond** [comment] 2020-08-26 12:26
> I've just hit this as well.
> 
> I worked around it with:
> 
> ```
> alertFilterRegexp: 'ABC$|^CephOSDNearFull$|^ABC'
> ```
> 
> A massive hack but since I use `helm-operator` to deploy these, I lose any changes I make to the daemonset every hour.

Thanks, this works for me as a workaround!
