### ISSUE TITLE
Helm Upgrade to 3.0.0 Fails with "field is immutable"

### ISSUE THREAD

**Issue by JoshuaAnickat** [weaveworks/kured#610] opened 2022-08-02 16:03 UTC
Currently running Kured 2.17.0 on AKS. 

```bash
$ kubectl get ds kured -n kured -o yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
    meta.helm.sh/release-name: kured
    meta.helm.sh/release-namespace: kured
  creationTimestamp: "2022-06-21T18:47:43Z"
  generation: 3
  labels:
    app: kured
    app.kubernetes.io/managed-by: Helm
    chart: kured-2.17.0
    heritage: Helm
    release: kured
```

Helm charts in the AKS cluster are being kept up to date via CI/CD. Kured upgrades have previously had no problems but have recently started failing. Below is the upgrade command that has recently started failing:

```bash
helm repo add kured https://weaveworks.github.io/kured
helm upgrade kured kured/kured --install --wait --create-namespace \
    --namespace kured \
    --set nodeSelector."kubernetes\.io/os"=linux
```

Here is the error:

```bash
2022-08-02 15:16:31.420912: Installing Kured.
2022-08-02 15:16:31.619685: "kured" has been added to your repositories
2022-08-02 15:16:33.468790: Error: UPGRADE FAILED: cannot patch "kured" with kind DaemonSet: DaemonSet.apps "kured" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kured", "app.kubernetes.io/name":"kured"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

I believe this issue might be related to [this one](https://github.com/Azure/aad-pod-identity/issues/600).

**Comment by JoshuaAnickat** [comment] 2022-08-02 17:48
Temporary workaround was to pin the chart to the currently installed version:

```bash
helm repo add kured https://weaveworks.github.io/kured
helm upgrade kured kured/kured --install --wait --create-namespace \
    --namespace kured \
    --version 2.17.0 \
    --set nodeSelector."kubernetes\.io/os"=linux
```

**Comment by ckotzbauer** [comment] 2022-08-02 19:14
As described in the chart changelog: You have to uninstall and reinstall the chart. A in-place upgrade is not possible. This is not a bug of the chart.

**Comment by ckotzbauer** [comment] 2022-08-09 05:18
Closing for now, please comment if you need any additional help @JoshuaAnickat

**Closed by ckotzbauer** 2022-08-09 05:18 UTC
Labels: question
